Repository Splint-Final-Project/Pickle-Time-Frontend, pull requests merged in 2024-06, with the labels that each got.

#30 홈 페이지 피클 컴포넌트 구현
  src/assets/icons/SpecialPickleCardArrowIcon.tsx
  src/assets/images/pickleCategoryImg-exercise.png
  src/assets/images/pickleCategoryImg-study.png
  src/assets/images/specialPickleCardBackImg.png
  src/components/picklecard/SpecialPickleCard.tsx
  src/components/picklecard/WholePickleCard.tsx
Labels: ✨ enhancement

#28 IntersectionObservRef훅 구현
  src/hooks/useIntersectionObserv.ts
Labels: ✨ enhancement

#32 홈 레이아웃 생성 및 적용
  src/Router.tsx
  src/components/common/BottomNav.tsx
  src/layouts/MainLayout.tsx
  src/pages/home/Home.tsx
  tsconfig.json
  vite.config.ts
Labels: ✨ enhancement

#36 feat [박현우] : ErrorBoundary component구현
  src/components/common/ErrorBoundary.tsx
Labels: ✨ enhancement

#35 [노은수] feat: 캐러셀 스타일 구현
  src/assets/images/.gitkeep
  src/assets/images/exercise.png
  src/assets/images/study.png
  src/assets/images/study2.png
  src/components/carousel/Carousel.tsx
  src/components/carousel/CarouselImg.tsx
  src/pages/home/Home.tsx
Labels: ✨ enhancement

#37 [홈] 전체 피클목록 탭, 무한스크롤 구현
  src/Router.tsx
  src/apis/pickle.api.ts
  src/apis/types/pickles.type.ts
  src/components/common/button/SortButtons.tsx
  src/components/picklecard/InfinitePickleCardList.tsx
  src/components/picklecard/InfinitePickleCardLoader.tsx
  src/components/picklecard/WholePickleCard.tsx
  src/constants/API.ts
  src/constants/BUTTON.ts
  src/constants/routes.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/profile/MyPage.tsx
  src/styles/commonStyles.ts
Labels: ✨ enhancement

#40 공통 input 컴포넌트 리펙토링(불필요한 파일 삭제 및 디자인 변경 및 리펙토링)
  src/assets/icons/DeleteInputValueIcon.tsx
  src/assets/icons/PasswordShowIcon.tsx
  src/components/common/inputs/CheckboxInput.tsx
  src/components/common/inputs/DefaultInput.tsx
  src/components/common/inputs/DropdownInput.tsx
  src/components/common/inputs/ErrorMessage.tsx
  src/components/common/inputs/Input.tsx
  src/components/common/inputs/Label.tsx
  src/components/common/inputs/PasswordInput.tsx
  src/components/common/inputs/ScoreInput.tsx
  src/components/common/inputs/TextInput.tsx
  src/components/common/inputs/TextareaField.tsx
  src/components/common/inputs/example.tsx
  src/components/common/inputs/formProps.tsx
Labels: 👍🏻 refactor

#42 [피클상세] 피클 상세 페이지 api연동 및 404페이지 추가
  src/Router.tsx
  src/apis/pickle.api.ts
  src/components/picklecard/WholePickleCard.tsx
  src/hooks/query/pickles/index.ts
  src/pages/NotFoundPage.tsx
  src/pages/pickles/PickleList.tsx
  src/pages/profile/MyPage.tsx
  src/utils/formatData.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ enhancement

#43 feat 홈페이지 인기, 마감 피클 리스트 컴포넌트 구현
  src/apis/pickle.api.ts
  src/components/picklecard/SpecialPickleCard.tsx
  src/components/picklecardlist/PickleCardList.Skeleton.tsx
  src/components/picklecardlist/PickleCardList.tsx
  src/components/picklecardlist/PickleCardListElement.tsx
  src/constants/API.ts
  src/hooks/query/pickles/index.ts
  src/hooks/useHeartButtonClick.ts
  src/layouts/MainLayout.tsx
  src/pages/home/Home.tsx
Labels: ✨ enhancement

#48 [홈] 하단 navbar 설정 및 레이아웃 수정
  public/icons/bottomNavbar/home.svg
  public/icons/bottomNavbar/marker.svg
  public/icons/bottomNavbar/message.svg
  public/icons/bottomNavbar/myPage.svg
  public/icons/bottomNavbar/myPickle.svg
  src/components/common/BottomNav.tsx
  src/layouts/MainLayout.tsx
  src/pages/home/Home.tsx
  src/styles/globalStyle.ts
Labels: ✨ enhancement, 🔨 fix

#53 디자인 시스템 확정에 따른 theme 재 설정
  src/pages/NotFoundPage.tsx
  src/styles/globalStyle.ts
  src/styles/theme.ts
  src/styles/types/theme.d.ts
Labels: ✨ enhancement

#52 인기,마감 피클리스트 섹션, 데이터가 없을 때는 버튼 hidden로직 추가
  src/components/picklecardlist/PickleCardList.tsx
Labels: ✨ enhancement

#58 [fix] theme 빌드에러 해결
  src/styles/theme.ts
Labels: 🔨 fix

#61 바텀 시트 모달 구현
  src/App.tsx
  src/components/common/modal/BottomSheetModal.tsx
  src/components/picklecardlist/PickleCardList.tsx
  src/hooks/useBottomSheetModal.ts
  src/hooks/zustand/useBottomSheetModalState.ts
Labels: ✨ enhancement

#50 전체피클목록 무한스크롤 로직 수정
  index.html
  src/apis/pickle.api.ts
  src/components/picklecard/InfinitePickleCardList.tsx
  src/components/picklecard/InfinitePickleCardLoader.tsx
  src/components/picklecard/WholePickleCard.tsx
  src/components/picklecard/WholePickleCardSkeleton.tsx
  src/hooks/query/pickles/index.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/profile/MyPage.tsx
Labels: 🐞 bug, 🔨 fix

#63 바텀시트 모달 로직 변경
  src/components/common/modal/BottomSheetModal.tsx
  src/hooks/useBottomSheetModal.ts
  src/hooks/zustand/useBottomSheetModal.ts
  src/hooks/zustand/useBottomSheetModalState.ts
Labels: 🔨 fix

#64 [홈] '전체 피클' 추가 및 카테고리 탭 변경
  src/components/common/button/SortButtons.tsx
  src/components/common/modal/BackDropModal.tsx
  src/components/picklecardlist/PickleCardListElement.tsx
  src/pages/home/Home.tsx
Labels: ✨ enhancement

#66 [마이페이지] 리뷰 생성 모달
  public/icons/tmpRating.png
  src/apis/pickle.api.ts
  src/apis/types/pickles.type.ts
  src/assets/icons/CloseIcon.tsx
  src/assets/icons/StarIcon.tsx
  src/components/common/modal/BottomSheetModal.tsx
  src/components/my-page/review/ReviewModal.tsx
  src/components/my-page/review/StarRating.tsx
  src/constants/PLACEHOLDER.ts
  src/hooks/query/pickles/index.ts
  src/mocks/handler/pickleHandlers.ts
  src/pages/home/Home.tsx
  src/styles/globalStyle.ts
Labels: ✨ enhancement

#73 [홈] 피클 생성 플로팅 버튼, 캐러셀 화살표, router 작업
  public/icons/createPickle.svg
  public/icons/leftBlackArrow.svg
  public/icons/rightBlackArrow.svg
  src/Router.tsx
  src/components/common/button/SortButtons.tsx
  src/components/picklecardlist/PickleCardList.tsx
  src/constants/routes.ts
  src/mocks/pickleCardData.tsx
  src/pages/auth/SignUp2.tsx
  src/pages/home/Home.tsx
Labels: ✨ enhancement

#75 결제창 관련 컴포넌트 생성
  src/assets/icons/checkIcon.svg
  src/assets/images/kakaopayLogo.png
  src/assets/images/tosspayLogo.png
  src/components/picklePayment/Benefits.tsx
  src/components/picklePayment/PaymentComponent.ts
  src/components/picklePayment/PaymentMeans.tsx
  src/components/picklePayment/PaymentSection.tsx
  src/components/picklePayment/PaymentTerms .tsx
  src/components/picklePayment/PicklePreviewCard.tsx
  src/components/picklePayment/PointDiscount.tsx
  src/components/picklePayment/TotalPayment.tsx
Labels: ✨ enhancement

#74 [피클상세] 상세페이지구현(보완필요)
  public/icons/back.svg
  public/icons/costIcon.svg
  public/icons/groupIcon.svg
  public/icons/locationIcon.svg
  public/icons/pickle-category/exercise.svg
  public/icons/pickle-category/hobby.svg
  public/icons/pickle-category/study.svg
  public/icons/timeIcon.svg
  src/apis/types/pickles.type.ts
  src/assets/icons/ArrowTopIcon.tsx
  src/components/common/button/BackButton.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/TopButton.tsx
  src/components/pickle-detail/Category.tsx
  src/components/pickle-detail/LikeCount.tsx
  src/components/pickle-detail/PickleTextInfo.tsx
  src/components/picklecard/SpecialPickleCard.tsx
  src/hooks/query/pickles/index.ts
  src/hooks/useHeartButtonClick.ts
  src/hooks/useScrollToTop.ts
  src/pages/pickles/Pickle.tsx
  src/styles/buttonStyles.ts
  src/styles/theme.ts
  src/styles/types/theme.d.ts
Labels: ✨ enhancement

#83 피클 생성 4페이지(결제) 1차 구현
  src/components/picklePayment/PaymentMeans.tsx
  src/components/picklePayment/PicklePreviewCard.tsx
  src/components/picklePayment/PointDiscount.tsx
  src/pages/pickles/CreatePickle4.tsx
  src/utils/paymentCall.ts
Labels: ✨ enhancement

#85 [refactor] 리뷰모달, 피클상세페이지 리팩토링
  src/Router.tsx
  src/apis/types/pickles.type.ts
  src/assets/icons/StarIcon.tsx
  src/components/my-page/review/ReviewModal.tsx
  src/components/my-page/review/StarRating.tsx
  src/components/pickle-detail/PickleTextInfo.tsx
  src/components/picklecard/InfinitePickleCardList.tsx
  src/constants/routes.ts
  src/pages/around/AroundMe.tsx
  src/pages/pickles/Pickle.tsx
  yarn.lock
Labels: 👍🏻 refactor

#90 fix생성 4페이지 수정
  src/pages/pickles/CreatePickle4.tsx
  src/utils/paymentCall.ts
Labels: 🔨 fix

#86 [refactor] 리뷰모달, 마감임박/인기급상승 전체보기, 레이아웃 구현 및 수정
  public/icons/backButton.svg
  public/icons/unreveal.svg
  public/images/category1.svg
  public/images/category2.svg
  public/images/category3.svg
  public/images/temporaryMarkerImage.png
  src/Router.tsx
  src/components/common/modal/BottomSheetModal.tsx
  src/components/my-page/review/ReviewModal.tsx
  src/components/pickleWholeList/Header.tsx
  src/components/picklecardlist/PickleCardList.tsx
  src/components/picklecardlist/PickleCardListElement.tsx
  src/constants/routes.ts
  src/layouts/MainLayout.tsx
  src/mocks/pickleCardData.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/SignUpStyled.ts
  src/pages/home/Home.tsx
  src/pages/pickles/CreatePickle1.tsx
  src/pages/pickles/CreatePickleStyled.ts
  src/pages/pickles/HotTimePickleList.tsx
  src/pages/pickles/PopularPickleList.tsx
  yarn.lock
Labels: ✨ enhancement, 👍🏻 refactor

#92 [피클상세] 변경된 실제 데이터 적용
  src/apis/types/pickles.type.ts
  src/components/pickle-detail/PickleTextInfo.tsx
  src/pages/pickles/Pickle.tsx
  src/utils/formatData.ts
Labels: 👍🏻 refactor

#95 채팅방 목록 페이지 구현 입니다
  src/components/chatList/CategoryFilterBar.tsx
  src/components/chatList/ChatList.tsx
  src/components/chatList/ChatListContainer.tsx
  src/components/chatList/ChatListSearchBar.tsx
  src/pages/chat/ConversationList.tsx
Labels: ✨ enhancement

#94 [refactor] 인기 급상승, 마감임박 페이지 수정
  src/components/pickleWholeList/PickleListCard.tsx
  src/components/pickleWholeList/PickleListHeader.tsx
  src/components/picklecardlist/PickleCardList.tsx
  src/components/picklecardlist/PickleCardListElement.tsx
  src/mocks/pickleCardListMockData.tsx
  src/mocks/pickleCardMockData.tsx
  src/pages/pickles/CreatePickleStyled.ts
  src/pages/pickles/HotTimePickleList.tsx
  src/pages/pickles/PopularPickleList.tsx
  src/styles/commonStyles.ts
Labels: ✨ enhancement, 👍🏻 refactor

#98 [내 주변] 가까운 피클 목록 카드 컴포넌트 구현
  src/components/common/BottomNav.tsx
  src/components/picklecard/AroundPickleCard.tsx
  src/pages/around/AroundMe.tsx
Labels: ✨ enhancement

#101 내피클 페이지 디자인
  src/Router.tsx
  src/assets/icons/AddressIcon.tsx
  src/assets/icons/ClockIcon.tsx
  src/assets/icons/PagenationNextArrow.tsx
  src/assets/icons/PagenationPrevArrow.tsx
  src/assets/images/categoryBgExercise.png
  src/assets/images/categoryBgHobby.png
  src/assets/images/categoryBgStudy.png
  src/assets/images/todayPickleCardBackImg.svg
  src/components/myPicklePage/MyPickleCard.tsx
  src/components/myPicklePage/MyPickleListContainer.tsx
  src/components/myPicklePage/PagenationBar.tsx
  src/components/myPicklePage/PickleStateFilterBar.tsx
  src/components/myPicklePage/TodayPickleCard.tsx
  src/components/myPicklePage/TodayPickleListContainer.tsx
  src/pages/pickles/MyPickles.tsx
Labels: ✨ enhancement

#104 내피클 페이지 컴포넌트 임시 목업 데이터 적용 테스트
  src/apis/pickle.api.ts
  src/components/myPicklePage/MyPickleCard.tsx
  src/components/myPicklePage/MyPickleListContainer.tsx
  src/components/myPicklePage/TodayPickleCard.tsx
  src/components/myPicklePage/TodayPickleListContainer.tsx
  src/constants/API.ts
  src/hooks/query/pickles/index.ts
  src/pages/pickles/MyPickles.tsx
Labels: ✨ enhancement

#103 [마이페이지] 페이지 UI 구현
  public/icons/emptyCheck.svg
  public/icons/filledCheck.svg
  public/icons/mypage-menu/pointIcon.svg
  public/icons/mypage-menu/reviewIcon.svg
  public/icons/mypage-menu/wishlistIcon.svg
  public/icons/rightArrowIcon.svg
  public/icons/settingIcon.svg
  src/Router.tsx
  src/assets/icons/StarIcon.tsx
  src/components/my-page/DynamicRender.tsx
  src/components/my-page/MenuList.tsx
  src/components/my-page/point/PointHistoryCard.tsx
  src/components/my-page/point/PointList.tsx
  src/components/my-page/review/Rating.tsx
  src/components/my-page/review/ReviewList.tsx
  src/components/my-page/wishlist/WishList.tsx
  src/components/picklecard/SpecialPickleCard.tsx
  src/constants/BUTTON.ts
  src/constants/routes.ts
  src/pages/profile/EditProfilePage.tsx
  src/pages/profile/MyPage.tsx
  src/styles/commonStyles.ts
Labels: ✨ enhancement

#108 리뷰 버튼 이벤트 구현 및 출석버튼 disabled 로직 구현 및 적용
  src/components/myPicklePage/MyPickleCard.tsx
  src/components/myPicklePage/TodayPickleListContainer.tsx
  src/utils/isButtonActive.ts
Labels: ✨ enhancement

#109 현재 위치와 피클 장소와의 사이 거리를 구해주는 함수 작성
  src/components/myPicklePage/TodayPickleListContainer.tsx
  src/utils/betweenLength.ts
Labels: ✨ enhancement

#110 시작시간과 현재시간을 비교하여 시간 메세지를 출력하는 함수 구현
  src/components/myPicklePage/TodayPickleListContainer.tsx
  src/utils/isButtonActive.ts
  src/utils/todayPickleCardUtils.ts
Labels: ✨ enhancement

#113 오늘의 피클 카드 배경에 캐릭터 추가 및 진행 중, 종료된 피클 데이터 api 연결
  src/assets/icons/character.svg
  src/components/myPicklePage/MyPickleListContainer.tsx
  src/components/myPicklePage/TodayPickleCard.tsx
Labels: ✨ enhancement

#116 피클 검색 후 화면 구현, alert->toast로 변경, 스타일 및 애니메이션 수정
  public/icons/dropdown.svg
  public/icons/search.svg
  public/icons/xCircle.svg
  src/Router.tsx
  src/components/pickleCreate/AreaInput.tsx
  src/components/pickleCreate/CreationPayment.tsx
  src/components/pickleCreate/ImgSelect.tsx
  src/components/pickleWholeList/PickleListCard.tsx
  src/constants/routes.ts
  src/pages/auth/SignIn_Email.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/SignUp2.tsx
  src/pages/pickles/JoinPickle.tsx
  src/pages/pickles/Pickle.tsx
  src/pages/pickles/PickleEdit.tsx
  src/pages/pickles/PickleSearchResults.tsx
  src/redirectors/OAuthSuccessRedirector.tsx
  src/redirectors/PickleCreationRedirector.tsx
  src/redirectors/PickleJoinRedirector.tsx
Labels: ✨ enhancement, 🔨 fix

#114 오늘의 피클카드 컨테이너 실제 데이터로 임시 변경
  src/assets/icons/character.svg
  src/components/myPicklePage/TodayPickleCard.tsx
  src/components/myPicklePage/TodayPickleListContainer.tsx
Labels: 🔨 fix

#117 [fix] Home Bottom Nav 레이아웃 오류 수정
  src/components/picklecardlist/PickleCardList.tsx
  src/pages/home/Home.tsx
Labels: 🔨 fix

#119 마이페이지 예외처리, 프로필 수정 리팩토링
  src/apis/types/pickles.type.ts
  src/apis/types/user.type.ts
  src/components/my-page/point/PointHistoryCard.tsx
  src/components/my-page/point/PointList.tsx
  src/components/my-page/review/ReviewList.tsx
  src/components/my-page/wishlist/WishList.tsx
  src/hooks/zustand/useAuth.ts
  src/pages/profile/EditProfilePage.tsx
Labels: 👍🏻 refactor

#121 오늘의 피클 데이터가 없을시 보여줄 ui 구현
  src/components/myPicklePage/TodayPickleListContainer.tsx
Labels: ✨ enhancement

#122 빈 데이터 메세지ui 컴포넌트 구현 및 피클 리스트 빈 데이터일 때 로직 구현
  src/assets/icons/emptyDataCharacter.svg
  src/components/common/EmptyDataMessage.tsx
  src/components/myPicklePage/MyPickleListContainer.tsx
Labels: ✨ enhancement

#123 [fix] 피클 생성페이지, 마이페이지(찜목록) 버그 처리
  src/apis/types/pickles.type.ts
  src/components/my-page/point/PointHistoryCard.tsx
  src/components/my-page/review/ReviewList.tsx
  src/components/my-page/wishlist/WishList.tsx
  src/components/pickleCreate/GoalSelect.tsx
  src/components/picklePayment/PointDiscount.tsx
  src/utils/formatData.ts
Labels: 🔨 hotfix

#125 데이터 없을 때 피클리스트 디자인 ui 수정
  src/components/myPicklePage/MyPickleListContainer.tsx
Labels: 🔨 fix

#128 [hotfix] 생성하기 버튼 추가
  src/pages/home/Home.tsx
Labels: 🔨 hotfix, ✨ enhancement

#129 커스텀 토스트 생성 및 적용
  public/icons/errorCharacterIcon.svg
  public/icons/mainCharacterIcon.svg
  src/components/common/Toast.tsx
  src/components/common/modal/ShareModal.tsx
  src/components/pickleCreate/AreaInput.tsx
  src/components/pickleCreate/CreationPayment.tsx
  src/hooks/query/like/index.ts
  src/hooks/query/pickles/index.ts
  src/hooks/zustand/useAuth.ts
  src/pages/auth/SignIn_Email.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/SignUp2.tsx
  src/pages/mapsearch/MapSearch.tsx
  src/pages/pickles/JoinPickle.tsx
  src/pages/pickles/PickleEdit.tsx
  src/redirectors/PickleCreationRedirector.tsx
  src/redirectors/PickleJoinRedirector.tsx
Labels: ✨ enhancement

#130 Main, Simple 레이아웃 / 마이페이지 프로필설정 아이콘 수정
  src/components/my-page/MenuList.tsx
  src/components/my-page/point/PointList.tsx
  src/layouts/MainLayout.tsx
  src/layouts/SimpleLayout.tsx
  src/pages/profile/MyPage.tsx
Labels: 👍🏻 refactor

#132 404(NotFoundPage) 구현
  index.html
  public/icons/sadCharacterIcon.svg
  src/pages/NotFoundPage.tsx
Labels: 👍🏻 refactor

#133 데이터가 없을 떄 보여줄 ui 스타일 수정
  src/components/common/EmptyDataMessage.tsx
Labels: 🔨 fix

#134 [hotfix] 내피클 attendance 버그 수정
  src/components/myPicklePage/TodayPickleListContainer.tsx
Labels: 🔨 hotfix

#135 일부 아이콘 이동 및 파일 변경
  public/icons/character.svg
  public/icons/checkIcon.svg
  public/icons/emptyDataCharacter.svg
  src/components/common/EmptyDataMessage.tsx
  src/components/myPicklePage/TodayPickleCard.tsx
  src/components/myPicklePage/TodayPickleListContainer.tsx
  src/components/picklePayment/PaymentTerms .tsx
Labels: 🔨 fix

#136 [refactor] 지도 높이 이슈해결, 마이페이지 데이터 없는 경우 리팩토링
  src/components/common/EmptyDataMessage.tsx
  src/components/my-page/point/PointList.tsx
  src/components/my-page/review/ReviewList.tsx
  src/components/my-page/wishlist/WishList.tsx
  src/pages/mapsearch/MapSearch.tsx
Labels: 🔨 fix, 👍🏻 refactor

#137 [refactor] 필요없는 import, 주석, 콘솔제거 스타일링 리팩토링
  src/apis/auth.api.ts
  src/apis/conversations.api.ts
  src/apis/pickle.api.ts
  src/apis/user.api.ts
  src/components/auth/SignInComponents.ts
  src/components/auth/SignUpComponents.ts
  src/components/carousel/Carousel.tsx
  src/components/chatList/ChatList.tsx
  src/components/chatList/ChatListSearchBar.tsx
  src/components/common/BottomNav.tsx
  src/components/common/EmptyDataMessage.tsx
  src/components/common/button/RoundButton.tsx
  src/components/common/button/SortButtons.tsx
  src/components/common/modal/AreaSelectModal.tsx
  src/components/common/modal/BackDropModal.tsx
  src/components/common/modal/BottomSheetModal.tsx
  src/components/common/tag/Tag.tsx
  src/components/message/Message.tsx
  src/components/my-page/DynamicRender.tsx
  src/components/my-page/TodayPickle.tsx
  src/components/my-page/edit/ActivityArea.tsx
  src/components/my-page/point/PointHistoryCard.tsx
  src/components/my-page/point/PointList.tsx
  src/components/my-page/review/ReviewList.tsx
  src/components/my-page/review/ReviewModal.tsx
  src/components/my-page/wishlist/WishList.tsx
  src/components/myPicklePage/MyPickleCard.tsx
  src/components/myPicklePage/MyPickleListContainer.tsx
  src/components/myPicklePage/PagenationBar.tsx
  src/components/myPicklePage/TodayPickleCard.tsx
  src/components/myPicklePage/TodayPickleListContainer.tsx
  src/components/pickle-detail/LikeCount.tsx
  src/components/pickle-detail/PickleTextInfo.tsx
  src/components/picklecard/AroundPickleCard.tsx
  src/components/picklecard/InfinitePickleCardList.tsx
  src/components/picklecard/SpecialPickleCard.tsx
  src/components/picklecard/WholePickleCard.tsx
  src/components/picklecard/WholePickleCardSkeleton.tsx
Labels: 👍🏻 refactor

#138 홈 전체 피클 tab에 따라 데이터 변경되도록 로직 수정, 리뷰모달 애니메이션 수정
  src/apis/pickle.api.ts
  src/apis/types/pickles.type.ts
  src/components/common/button/SortButtons.tsx
  src/components/my-page/point/PointHistoryCard.tsx
  src/components/my-page/review/ReviewModal.tsx
  src/components/picklecard/InfinitePickleCardList.tsx
  src/components/picklecardlist/PickleCardListElement.tsx
  src/hooks/query/pickles/index.ts
  src/layouts/SimpleLayout.tsx
  src/pages/home/Home.tsx
  src/pages/pickles/Pickle.tsx
Labels: ✨ enhancement, 🔨 fix

#142 페이지별 자잘한 스타일 리팩토링
  public/icons/kakaoBtnIcon.svg
  public/icons/naverBtnIcon.svg
  src/components/common/modal/KeepCreatingModal.tsx
  src/pages/auth/Admin.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignIn_Email.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/SignUp2.tsx
  src/pages/auth/SignUpStyled.ts
  src/pages/chat/Chat.style.ts
  src/pages/chat/ConversationList.tsx
  src/pages/home/Home.tsx
  src/pages/mapsearch/MapSearch.tsx
  src/pages/pickles/CreatePickle.tsx
  src/pages/pickles/CreatePickleStyled.ts
  src/pages/pickles/HotTimePickleList.tsx
  src/pages/pickles/JoinPickle.tsx
  src/pages/pickles/MyPickles.tsx
  src/pages/pickles/Pickle.tsx
  src/pages/pickles/PickleEdit.tsx
  src/pages/pickles/PickleSearchResults.tsx
  src/pages/pickles/PopularPickleList.tsx
  src/pages/profile/MyPage.tsx
  src/redirectors/LoginRedirector.tsx
  src/redirectors/OAuthSuccessRedirector.tsx
  src/redirectors/PickleCreationRedirector.tsx
  src/styles/globalStyle.ts
Labels: 👍🏻 refactor

#141 인기 급상승 피클, 마감 임박 피클 필터링
  src/apis/pickle.api.ts
  src/components/myPicklePage/TodayPickleListContainer.tsx
  src/components/pickleWholeList/PickleListCard.tsx
  src/hooks/query/pickles/index.ts
  src/pages/chat/Conversation.tsx
  src/pages/chat/OneToOne.tsx
  src/pages/pickles/HotTimePickleList.tsx
  src/pages/pickles/JoinPickle.tsx
  src/pages/pickles/Pickle.tsx
  src/pages/pickles/PickleEdit.tsx
  src/pages/pickles/PopularPickleList.tsx
Labels: ✨ enhancement, 🔨 fix

#144 [refactor] pages 파일명 형식통일, 카드 hover 스타일링 추가, joinPickle(useEffect) 누락 추가
  src/Router.tsx
  src/components/common/modal/AreaSelectModal.tsx
  src/components/myPicklePage/MyPickleCard.tsx
  src/components/pickleWholeList/PickleListCard.tsx
  src/components/picklecard/SpecialPickleCard.tsx
  src/components/picklecard/WholePickleCard.tsx
  src/components/picklecardlist/PickleCardListElement.tsx
  src/pages/NotFound.page.tsx
  src/pages/auth/SignIn.page.tsx
  src/pages/auth/SignInEmail.page.tsx
  src/pages/auth/SignUp.page.tsx
  src/pages/auth/SignUp2.page.tsx
  src/pages/chat/Conversation.page.tsx
  src/pages/chat/ConversationList.page.tsx
  src/pages/chat/OneToOne.page.tsx
  src/pages/home/Home.page.tsx
  src/pages/mapsearch/MapSearch.page.tsx
  src/pages/pickles/CreatePickle.page.tsx
  src/pages/pickles/HotTimePickleList.page.tsx
  src/pages/pickles/JoinPickle.page.tsx
  src/pages/pickles/MyPickle.page.tsx
  src/pages/pickles/PickleDetail.page.tsx
  src/pages/pickles/PickleEdit.page.tsx
  src/pages/pickles/PickleSearchResults.page.tsx
  src/pages/pickles/PopularPickleList.page.tsx
  src/pages/profile/EditProfile.page.tsx
Labels: 🔨 fix, 👍🏻 refactor

#147 [hotfix] Logo 교체
  public/images/logotext.svg
  src/pages/auth/SignIn.page.tsx
Labels: 🔨 hotfix

#146 [홈] 피클 데이터 없는경우 처리 / 로그인회원가입페이지 소개문구 수정
  public/icons/noPickleIcon.svg
  src/components/common/NoPickle.tsx
  src/components/myPicklePage/TodayPickleListContainer.tsx
  src/components/pickleWholeList/PickleListCard.tsx
  src/components/picklecard/InfinitePickleCardList.tsx
  src/components/picklecardlist/PickleCardList.tsx
  src/pages/auth/SignIn.page.tsx
  src/pages/auth/SignUp.page.tsx
  src/pages/auth/SignUp2.page.tsx
  src/pages/pickles/HotTimePickleList.page.tsx
  src/pages/pickles/PopularPickleList.page.tsx
Labels: 👍🏻 refactor

#148 내주변 지도 로딩 스패너 추가
  src/pages/mapsearch/MapSearch.page.tsx
Labels: ✨ enhancement
